### ISSUE TITLE
can you support page filter as well?

### ISSUE THREAD

**Issue by dive2Pro** [mlava/workspaces#1]
<img width="734" alt="image" src="https://user-images.githubusercontent.com/23192045/193468469-214edd5a-adfc-4557-90a0-1f406af5f3d6.png">

like this image, if there are filters working in that page when i creating a workspace, i want the filters to continue working after i switch back to the workspace

thanks for your work!

**Comment by mlava** [comment]
@dive2Pro 
this is only for the main content pane, right?
or do you want linked refs and right sidebar filters as well?

**Comment by dive2Pro** [comment]
> @dive2Pro this is only for the main content pane, right? or do you want linked refs and right sidebar filters as well?

yeah, that would be wonderful!

**Comment by mlava** [comment]
@dive2Pro 
Filters for both main window and right sidebar windows are implemented in next update https://github.com/Roam-Research/roam-depot/pull/227
Just need to wait for Roam team to review and approve.

**Comment by Stvad** [comment]
Came here to request supporting filters for the linked references from the main page, not entirely sure if this implies that they should already work 😅 

![image](https://user-images.githubusercontent.com/81347/212982349-2fa642d8-7e5f-439c-94fd-42b79f895c74.png)

This configuration does not produce a desired result though 🤔  (which would be to filter daily page references to include "reading inbox" and exclude "DONE")

**Comment by Stvad** [comment]
ok, skimming the code this doesn't seem to be supported :( Will create a new issue for that!
