### ISSUE TITLE
Can't create workspaces. Error in colsole

### ISSUE THREAD

**Issue by MaxLinWorm** [mlava/workspaces#10]
Hey man, great extension, thanks a bunch.

I keep getting this error when trying to create a new workspace:

![image](https://user-images.githubusercontent.com/68432385/222539392-d5ca9e10-a7e0-403a-8610-4c102c514288.png)

route-app.js:2099 Uncaught (in promise) Error: Assert failed: (string? block-uid)
    at Object.eval [as getSidebarWindowFilters] (route-app.js:2099:264)
    at k (9338392e-11cb-4cbe-8a2e-1cd00f9633a1:1:40376)
eval @ route-app.js:2099
k @ 9338392e-11cb-4cbe-8a2e-1cd00f9633a1:1
await in k (async)
callback @ 9338392e-11cb-4cbe-8a2e-1cd00f9633a1:1
(anonymous) @ main.js?__WB_REVISION__=d89875281e0d308044a4ba7575cb33ac:10217
(anonymous) @ main.js?__WB_REVISION__=d89875281e0d308044a4ba7575cb33ac:7697
a1 @ route-app.js:2224
l @ route-app.js:781
m @ route-app.js:782
(anonymous) @ main.js?__WB_REVISION__=d89875281e0d308044a4ba7575cb33ac:4613
(anonymous) @ main.js?__WB_REVISION__=d89875281e0d308044a4ba7575cb33ac:4613
(anonymous) @ main.js?__WB_REVISION__=d89875281e0d308044a4ba7575cb33ac:8963
Exa @ main.js?__WB_REVISION__=d89875281e0d308044a4ba7575cb33ac:4605
t.exports @ f8790bf4-7d41-4dfd-90b7-f8ca3ef7b83f:2
g.<computed> @ f8790bf4-7d41-4dfd-90b7-f8ca3ef7b83f:2
b @ f8790bf4-7d41-4dfd-90b7-f8ca3ef7b83f:2
x @ f8790bf4-7d41-4dfd-90b7-f8ca3ef7b83f:2

Also saw that my auto-saved workspaces don't include my sidebar items.

**Comment by mlava** [comment]
Hi,
Sorry for the trouble.
Could you check you're on the most recent version (19). I thought I had fixed that error recently...

Also, can you confirm what elements you're trying to save in a workspace? DNP vs normal note page. What's in the sidebar (outline, graph, blockrefs). Thanks

**Comment by mlava** [comment]
Never mind. I found the bug.
Pushing a fix. https://github.com/Roam-Research/roam-depot/pull/589
Sorry.

**Comment by MaxLinWorm** [comment]
No trouble at all. Incredible support, thanks a bunch
