### ISSUE TITLE
A save command to manually replace/update current workspace definition

### ISSUE THREAD

**Issue by zzdoo** [mlava/workspaces#2]
Great work, thank you! 
Would you consider adding a save command to manually replace/update workspace definition selected from current state？

**Comment by mlava** [comment]
Yes, it's on my todo list 🙂

**Comment by mlava** [comment]
@zzdoo this is now implemented in https://github.com/Roam-Research/roam-depot/pull/281
It needs to be reviewed and approved before it will appear in your graph.
I hope it works as expected!
