### ISSUE TITLE
Can't save workspaces after opening references from within the sidebar

### ISSUE THREAD

**Issue by alexzadeh** [mlava/workspaces#4]
Hi,

* Open a page that has references in the sidebar by shift-clicking it
* Click on the reference number in the sidebar to open the references in the sidebar
* Open the command palette and enter the "Create workspace from current state" command

-> Nothing happens

I thought at first the issue was simply having references showing in the sidebar but actually if you open the references from the main window by shift clicking them the "Create workspace from current state command" works ok. 

Thanks

**Comment by mlava** [comment]
Hi @alexzadeh thanks for reporting.
I don't actually follow, sorry. I assume you are talking about block references using (( ))?
Could you make me a short video showing it, perhaps with you narrating the issue?
Cheers!

**Comment by alexzadeh** [comment]
![Roam Research - alexzadeh - November 9th 2022 - 08-11-2022 - 12 46 31@2x](https://user-images.githubusercontent.com/11060179/200567411-bf613c79-949d-4e65-9771-9e8f293d1ae3.jpg)

Here's an example. I opened the page 'Dummy Page' in the sidebar, then clicked on the references (3) to open them in the sidebar.

Selecting "Create Workspace from current state" while Roam is like this no longer shows the save prompt ("What do you want to call this Workspace?"). 

After closing the references in the sidebar selecting "Create Workspace from current state" then works.

**Comment by mlava** [comment]
Hi again,
Thanks for the above. I don't know how to open references in the sidebar - could you tell me how to do that?
Mark

**Comment by alexzadeh** [comment]
Hi Mark, you click the number of references, e.g. clicking '2':

![References 1](https://user-images.githubusercontent.com/11060179/200858562-c28e407f-9488-452f-b454-91ddd55254ea.jpg)

shows the References like this:

![References 2](https://user-images.githubusercontent.com/11060179/200858673-d7e511a4-f8e9-4653-bf9b-472708d53c56.jpg)

**Comment by mlava** [comment]
Sorry, got it.
Found the bug and pushed a fix to Roam Depot. It has to be reviewed and approved but then you should be good to go.
Thanks for reporting!
https://github.com/Roam-Research/roam-depot/pull/315

**Comment by mlava** [comment]
@alexzadeh this pr is merged and I can confirm it's working on my end now.
PLease let me know if any further issues.
Thanks again!

**Comment by alexzadeh** [comment]
Thanks!
