### ISSUE TITLE
Support main page references filters

### ISSUE THREAD

**Issue by Stvad** [mlava/workspaces#7]
Currently, the main page linked references are ignored, it'd be great if extension could support them!

![image](https://user-images.githubusercontent.com/81347/212983669-4a5466a6-e68c-4ac4-9e6d-c0c203cf0460.png)

**Comment by mlava** [comment]
Hi @Stvad 
This is a good idea... on my list of things to add

**Comment by mlava** [comment]
This is now implemented @Stvad 

You will need to wait for the RR team to review and approve before it's available.

https://github.com/Roam-Research/roam-depot/pull/458
