### ISSUE TITLE
Allow "partial application" of workspaces

### ISSUE THREAD

**Issue by Stvad** [mlava/workspaces#8]
The request is that if a part of workspace configuration is missing - don't touch that part of Roam 

For example: If I'd like to restore the state of the main page while keeping the sidebar intact, I might have the following configuration:
![image](https://user-images.githubusercontent.com/81347/212986246-fad3699d-7f78-47cc-ada8-b05848c2d686.png)

Right now that would cause the right sidebar to be closed and cleared, while I believe it should stay intact

I think this actually works partially (e.g. Restoring state of sidebar without touching the main page works), but it'd be great if it were to work consistently across all the properties!

**Comment by mlava** [comment]
@Stvad this is a really good idea.
On my list of things to add. Cheers!

**Comment by mlava** [comment]
@Stvad I've fixed this issue with right sidebar clearing. All other parts of the Workspace definition are already optional. I think this should work as you hope. Will need to be approved before available... https://github.com/Roam-Research/roam-depot/pull/521
